UKGovernmentBEIS/dsit-dvs-register

DVSRegister.BusinessLogic/DVSRegister.BusinessLogic.csproj
DVSRegister.BusinessLogic/Models/PreAssessment/PreAssessmentDto.cs
DVSRegister.BusinessLogic/Services/PreAssessment/IPreAssessmentService.cs
DVSRegister.BusinessLogic/Services/PreAssessment/PreAssessmentService.cs
DVSRegister.CommonUtility/AWS/ISecretManager.cs
DVSRegister.CommonUtility/AWS/SecretManager.cs
DVSRegister.CommonUtility/Constants.cs
DVSRegister.CommonUtility/DVSRegister.CommonUtility.csproj
DVSRegister.CommonUtility/Helper.cs
DVSRegister.Data/DVSRegister.Data.csproj
DVSRegister.Data/DVSRegisterDbContext.cs
DVSRegister.Data/GenericRepository.cs
DVSRegister.Data/IGenericRepository.cs
DVSRegister.UnitTests/BusinessLogic/PreAssessment/PreAssessmentServiceTests.cs
DVSRegister.UnitTests/DVSRegister.UnitTests.csproj
DVSRegister.UnitTests/DVSRegister/HomeControllerTests.cs
DVSRegister.UnitTests/GlobalUsings.cs
DVSRegister.sln
DVSRegister/DVSRegister.csproj
DVSRegister/appsettings.Dev.json
DVSRegister/appsettings.Development.json
DVSRegister/appsettings.Prod.json
DVSRegister/appsettings.Staging.json

* Add Business Logic Layer - folder structure ,sample classes and interface (DVSRegister.BusinessLogic)
* Add Data Access Layer - folder structure and sample classes and interface (DVSRegister.Data)
* Add Unit Tests - folder structure and sample unit test classe (DVSRegister.UnitTests)
* Add Common Utility - folder structure Sample static helper class, interfaces (DVSRegister.CommonUtility)

Create Project Structure

---

.dockerignore
Dockerfile

Adds a `Dockerfile` and `.dockerignore ` to containerize the repo and dockerize the repo. 
User Story - https://dev.azure.com/BEIS-DevOps/DVS%20Register/_workitems/edit/29326

feat(docker): Add Dockerfile

---

DVSRegister/Views/PreRegistration/ApplicationComplete.cshtml
DVSRegister/Views/PreRegistration/Country.cshtml

Part of [User Story 28242](https://dev.azure.com/BEIS-DevOps/DVS%20Register/_workitems/edit/28242)
: Pre-registration: Application complete, 
Part of [User Story 29946](https://dev.azure.com/BEIS-DevOps/DVS%20Register/_workitems/edit/29946)
: Pre-registration: List all the countries and territories your business currently trades in

Country selection page and Application complete page

---

DVSRegister/Views/PreRegistration/Country.cshtml

Add line break

---

DVSRegister/Views/Error/ServiceIssue.cshtml
DVSRegister/Views/PreRegistration/Contact.cshtml
DVSRegister/Views/PreRegistration/Country.cshtml
DVSRegister/Views/PreRegistration/SelectApplicationSponsor.cshtml
DVSRegister/Views/PreRegistration/Sponsor.cshtml
DVSRegister/Views/PreRegistration/StartPage.cshtml
DVSRegister/Views/Shared/_Layout.cshtml
DVSRegister/wwwroot/css/components/checkbox.scss
DVSRegister/wwwroot/css/main.css
DVSRegister/wwwroot/css/main.scss
DVSRegister/wwwroot/css/site.css

In figma: ![image](https://github.com/UKGovernmentBEIS/dsit-dvs-register/assets/5901665/f64888db-b7ec-4b47-8044-7b6b4b64e64d)

Design feedback updates

---

DVSRegister.BusinessLogic/Services/CAB/CabService.cs
DVSRegister.BusinessLogic/Services/CAB/ICabService.cs
DVSRegister.CommonUtility/Constants.cs
DVSRegister.Data/CAB/CabRepository.cs
DVSRegister.Data/CAB/ICabRepository.cs
DVSRegister/Controllers/CabController.cs
DVSRegister/DVSRegister.csproj
DVSRegister/Models/CAB/DateViewModel.cs
DVSRegister/Startup.cs
DVSRegister/Views/Cab/ConfirmityExpiryDate.cshtml
DVSRegister/Views/Cab/ConfirmityIssueDate.cshtml
DVSRegister/Views/Cab/HasSupplementaryScheme.cshtml
DVSRegister/Views/Cab/SelectIdentityProfiles.cshtml
DVSRegister/Views/Cab/SelectRoles.cshtml
DVSRegister/Views/Cab/SelectSupplementarySchemes.cshtml
DVSRegister/Views/PartialViews/_ErrorSummaryView.cshtml

…ntity profiles, supplementary sheme, conformity issue and expiry dates

feat(cab-portal): certificate info submission form pages 

---

DVSRegister.CommonUtility/DVSRegister.CommonUtility.csproj
DVSRegister.CommonUtility/Helper.cs
DVSRegister/Controllers/LoginController.cs
DVSRegister/Models/CAB/CreatePasswordViewModel.cs
DVSRegister/Models/CAB/EnterCodeViewModel.cs
DVSRegister/Models/CAB/LoginPageViewModel.cs
DVSRegister/Models/CAB/MFARegistrationViewModel.cs
DVSRegister/Views/Login/CreatePassword.cshtml
DVSRegister/Views/Login/EnterCode.cshtml
DVSRegister/Views/Login/LoginPage.cshtml
DVSRegister/Views/Login/MFAConfirmation.cshtml
DVSRegister/Views/Login/MFARegistration.cshtml
DVSRegister/Views/Login/SignUpComplete.cshtml
DVSRegister/Views/Login/StartPage.cshtml

CAB portal onboarding pages

---

DVSRegister.BusinessLogic/AutomapperProfile.cs
DVSRegister.BusinessLogic/Models/CAB/CertificateInfoDto.cs
DVSRegister.BusinessLogic/Models/CAB/ProviderDto.cs
DVSRegister.BusinessLogic/Services/CAB/CabService.cs
DVSRegister.BusinessLogic/Services/CAB/ICabService.cs
DVSRegister.CommonUtility/Models/Enums/ProviderStatusEnum.cs
DVSRegister.Data/CAB/CabRepository.cs
DVSRegister.Data/CAB/ICabRepository.cs
DVSRegister.Data/DVSRegisterDbContext.cs
DVSRegister.Data/Entities/CertificateInformation.cs
DVSRegister.Data/Entities/CertificateReview.cs
DVSRegister.Data/Entities/Provider.cs
DVSRegister.Data/Migrations/20240618154147_DropCertInfoAndReviewTables.Designer.cs
DVSRegister.Data/Migrations/20240618154147_DropCertInfoAndReviewTables.cs
DVSRegister.Data/Migrations/20240618155650_CreateProviderAndModifyCertTables.Designer.cs
DVSRegister.Data/Migrations/20240618155650_CreateProviderAndModifyCertTables.cs
DVSRegister/Controllers/CabController.cs

Certificate information table splitted - db change and associated code changes

---

DVSRegister.BusinessLogic/Services/PreRegistration/URNService.cs
DVSRegister/Views/PreRegistration/ApplicationComplete.cshtml

fix(urn-number): epoch number

---

DVSRegister/Models/PreRegistration/CompanyViewModel.cs

parent company name validation added

fix(pre-reg):parent company name validation

---

DVSRegister.BusinessLogic/Services/Register/IRegisterService.cs
DVSRegister/Controllers/RegisterController.cs
DVSRegister/Models/Register/RegisterPublishLogsViewModel.cs
DVSRegister/Views/Register/Updates.cshtml

feat(register):updates screen integration

feat(register):updates screen integration

---

DVSRegister/DVSRegister.csproj
DVSRegister/Models/PreRegistration/SponsorViewModel.cs
DVSRegister/Views/PartialViews/_ErrorSummaryView.cshtml
DVSRegister/Views/PartialViews/_PreRegSpecificErrorsView.cshtml
DVSRegister/Views/PartialViews/_SpecificErrorsView.cshtml
DVSRegister/Views/PreRegistration/ApplicationComplete.cshtml
DVSRegister/Views/PreRegistration/Company.cshtml
DVSRegister/Views/PreRegistration/Contact.cshtml
DVSRegister/Views/PreRegistration/Country.cshtml
DVSRegister/Views/PreRegistration/PartialViews/_CountrySummaryHideAll.cshtml
DVSRegister/Views/PreRegistration/PartialViews/_CountrySummaryShowAll.cshtml
DVSRegister/Views/PreRegistration/SelectApplicationSponsor.cshtml
DVSRegister/Views/PreRegistration/Sponsor.cshtml
DVSRegister/Views/PreRegistration/StartPage.cshtml
DVSRegister/Views/PreRegistration/Summary.cshtml
DVSRegister/Views/Shared/_Layout.cshtml
DVSRegister/Views/Shared/_Layout_CAB.cshtml

Several updates to form fields, page titles and error formatting based on feedback from accessibility audit.

Accessibility updates to pre reg

---

DVSRegister/Controllers/CabProviderController.cs
DVSRegister/Controllers/CabServiceController.cs
DVSRegister/Views/CabProvider/BeforeYouStart.cshtml
DVSRegister/Views/CabProvider/LandingPage.cshtml
DVSRegister/Views/CabService/BeforeYouStart.cshtml
DVSRegister/Views/CabService/LandingPage.cshtml

Added new Cab provider and Cab Service controllers and views.

Add new cab service controllers and views

---

DVSRegister/Controllers/CabProviderController.cs
DVSRegister/Models/CAB/Provider/ProfileSummaryViewModel.cs
DVSRegister/Views/CabProvider/BeforeYouStart.cshtml
DVSRegister/Views/CabProvider/RegisteredName.cshtml
DVSRegister/Views/CabProvider/TradingName.cshtml

Added the Cab-Provider profile first 3 screens.

feat(cab-provider) : provider profile screens

---

DVSRegister/Controllers/CabServiceController.cs
DVSRegister/Middleware/BasicAuthMiddleware.cs
DVSRegister/Middleware/ExceptionHandlerMiddleware.cs
DVSRegister/Models/UI/TextBoxViewModel.cs
DVSRegister/Views/CabService/CertificateUploadPage.cshtml
DVSRegister/Views/CabService/ConfirmityExpiryDate.cshtml
DVSRegister/Views/CabService/ConfirmityIssueDate.cshtml
DVSRegister/Views/CabService/ServiceSummary.cshtml
DVSRegister/Views/PartialViews/_TextBoxView.cshtml

1. Updated inner exception log in new lines to single line
2. Certificate file upload and download along with updates in textbox partial view and fixes in successive screens

Cab service screens

---

DVSRegister/Controllers/CabServiceController.cs
DVSRegister/Models/CAB/Service/CertificateFileViewModel.cs
DVSRegister/Models/CAB/Service/ServiceSummaryViewModel.cs
DVSRegister/Views/CabService/CertificateUploadPage.cshtml
DVSRegister/Views/CabService/HasSupplementarySchemesInput.cshtml
DVSRegister/Views/CabService/ProviderRoles.cshtml
DVSRegister/Views/CabService/SupplementarySchemes.cshtml

1. Select roles screens
2. Select supplementary shceme screens

Submit service screens

---

DVSRegister.Data/DVSRegister.Data.csproj

Package update from 8.0.0 to 8.0.1

fix(dvsregister-data):explicitly add latest asn1 package

---

DVSRegister.Data/Register/RegisterRepository.cs
DVSRegister/Views/Cab/ProviderOverview.cshtml
DVSRegister/Views/Register/ProviderDetails.cshtml
DVSRegister/Views/Register/Register.cshtml

1. Fix - provider details filter to show published services
2. Registered name and trading name corrections

merge dev to staging

---

DVSRegister/Middleware/SecurityHeadersMiddleware.cs

Removed the Nonce implementation and added the headers as per the bug.

feat(dvs-45):Removed the Nonce implementation and added the headers.

---

DVSRegister/Views/Cab/ProviderOverview.cshtml

Filtered the statuses only to submitted published and rejected on provider overview.

feat(dvs-84):filtered the statuses only to submitted published and rejected

---

DVSRegister.BusinessLogic/Services/CAB/CabService.cs
DVSRegister.BusinessLogic/Services/CAB/ICabService.cs
DVSRegister.Data/CAB/CabRepository.cs
DVSRegister.Data/CAB/ICabRepository.cs
DVSRegister.Data/Entities/ProviderProfile.cs
DVSRegister.Data/Migrations/20241111110830_AddCabEditedTime.Designer.cs
DVSRegister.Data/Migrations/20241111110830_AddCabEditedTime.cs
DVSRegister/Controllers/CabController.cs
DVSRegister/Controllers/CabProviderController.cs
DVSRegister/Extensions/HtmlExtensions.cs
DVSRegister/Views/Cab/ProviderOverview.cshtml
DVSRegister/Views/Cab/ProviderProfileDetails.cshtml
DVSRegister/Views/Cab/ProviderServiceDetails.cshtml

1. New timestamp field for to capture edit time
2. Edit feature changes - all edit pages changed to db calls instead of session, and provider edit condition changes

Dvs 99 changes that can be made after certificate is approved

---

DVSRegister.BusinessLogic/Services/CAB/CabService.cs
DVSRegister.BusinessLogic/Services/CAB/ICabService.cs
DVSRegister.CommonUtility/Models/Enums/ActionEnum.cs
DVSRegister.CommonUtility/Models/Enums/EventTypeEnum.cs
DVSRegister.CommonUtility/Models/Enums/TeamEnum.cs
DVSRegister.Data/CAB/CabRepository.cs
DVSRegister.Data/CAB/ICabRepository.cs
DVSRegister.Data/DVSRegisterDbContext.cs
DVSRegister.Data/Entities/Event.cs
DVSRegister.Data/Migrations/20241113172545_AddEventTable.Designer.cs
DVSRegister.Data/Migrations/20241113172545_AddEventTable.cs
DVSRegister.Data/Models/EventEntry.cs
DVSRegister.Data/User/UserRepository.cs
DVSRegister/Controllers/CabController.cs
DVSRegister/Controllers/CabProviderController.cs
DVSRegister/Controllers/CabServiceController.cs

Dvs 90 event table

---

DVSRegister/Views/Register/PartialViews/_NotificationBanner.cshtml
DVSRegister/Views/Register/Updates.cshtml
DVSRegister/wwwroot/css/components/notification-banner.scss
DVSRegister/wwwroot/css/main.css
DVSRegister/wwwroot/css/main.scss

DVS-126: Changed max width and added banner to updates page

---

DVSRegister/Views/Register/ProviderDetails.cshtml

fix(register) : add sentence for when no identity profile is selected

---

DVSRegister/Views/Register/ProviderDetails.cshtml

fix(reg-mangement) change basic info to provider info

fix(reg-mangement) change basic info to provider info

---

DVSRegister/Views/DSITEdit2i/ProviderChangesApproved.cshtml

feat(reg-management): add text to accepted a request to update provider information

feat(reg-management): add text to accepted a request to update provider information

---

DVSRegister/Views/DSITEdit2i/ProviderChangesCancelled.cshtml

feat(reg-management): add text to show update request is cancelled

feat(reg-management): add text to show update request is cancelled

---

DVSRegister/Views/DSITEdit2i/ServiceChangesApproved.cshtml

feat(reg-management): add text to show a request to update service information was accepted

feat(reg-management): add text to show a request to update service information was accepted

---

DVSRegister/Views/CabService/InformationSubmitted.cshtml
DVSRegister/Views/Consent/Consent.cshtml
DVSRegister/Views/Consent/ConsentSuccess.cshtml

fix(reg-management): change content in cab service and consent

fix(reg-management): change content in cab service and consent

---

DVSRegister/Views/Cab/PartialViews/_ServiceDetailsView.cshtml
DVSRegister/Views/CabService/ServiceSummary.cshtml
DVSRegister/Views/Consent/PartialViews/_ServiceDetailsView.cshtml
DVSRegister/Views/Consent/ProceedApplicationConsent.cshtml

fix(reg-management): fix spelling mistake and replaced 'click' with 'select'

fix(reg-management): fix spelling mistake and replaced 'click' with 'select'

---

DVSRegister/Views/Consent/ProceedApplicationConsentSuccess.cshtml

fix(reg-management): delete first sentance in first paragraphy and change you will to you'll

fix(reg-management): delete first sentance in first paragraphy and change you will to you'll

---

DVSRegister/Views/Login/MFADescription.cshtml
DVSRegister/Views/RemoveProvider2i/RemoveProviderSuccess.cshtml

fix(reg-management): change content in remove service provider page and mfa description

fix(reg-management): change content in remove service provider page and mfa description

---

DVSRegister/Views/Login/MFARegistration.cshtml
DVSRegister/Views/RemoveProvider2i/RemoveProviderDetails.cshtml

fix(reg-management): change h2 heading and paragraph

fix(reg-management): change h2 heading and paragraph

---

DVSRegister/Models/CAB/Service/ServiceSummaryViewModel.cs
DVSRegister/appsettings.Production.json

Register:  Prod deployment 10th March 2025

---

DVSRegister.BusinessLogic/Services/RemoveProvider2i/RemoveProvider2iService.cs
DVSRegister.Data/RemoveProvider/RemoveProviderRepository.cs

fix(remove-2i): corrections in refactored code for update removal email notification, clear removal fields while updating status by priority

---

DVSRegister.Data/CAB/CabRepository.cs
DVSRegister.Data/CabTransfer/CabTransferRepository.cs
DVSRegister/Extensions/HtmlExtensions.cs
DVSRegister/Views/Cab/ProviderOverview.cshtml

feat(cab-transfer): retain under reassignment status on approving transfer request, update on certificate upload
